site_name: "Nbt Crafting"
site_author: "Siphalor"
site_description: "The official wiki of Nbt Crafting"

repo_name: "GitHub"
repo_url: "https://github.com/Siphalor/nbt-crafting"
edit_uri: "../nbt-crafting-wiki/edit/v1/docs/"

extra:
    logo: "img/logo.png"
    version: "v1"
    nav_links:
      - text: "Nbt Crafting v2 wiki"
        icon: "book"
        url: "../v2"
      - text: "Curseforge"
        icon: "fire"
        url: "https://www.curseforge.com/minecraft/mc-mods/nbt-crafting"
      - text: "Discord"
        icon: "chat-empty"
        url: "https://discord.gg/6gaXmbj"

nav:
    - Home: "home.md"
    - Recipe Parts:
        - Ingredients:
            - Ingredients: "recipe-parts/ingredients/ingredients.md"
            - Remainders: "recipe-parts/ingredients/remainders.md"
        - Results: "recipe-parts/results.md"
    - Recipe Types:
        - Vanilla Recipes: "recipe-types/vanilla.md"
        - Anvil Recipes: "recipe-types/anvil.md"
        - Brewing Recipes: "recipe-types/brewing.md"
        - Cauldron Recipes: "recipe-types/cauldron.md"
        - Modded Recipes: "recipe-types/modded.md"
    - Dynamic Data:
        - Dollars: "dynamic-data/dollars.md"
    - Hints for modders: "modders.md"
    - Utilities: "utilities.md"

markdown_extensions:
    - attr_list
    - admonition
    - fontawesome_markdown
    - pymdownx.details
      #- pymdownx.tabbed
    - pymdownx.tasklist
    - toc:
        permalink: true

theme:
    name: "custommill"
    favicon: "img/favicon.ico"
    main_color: "#3e7726"

extra_css:
    - css/extra.css
