site_name: "Nbt Crafting"
site_author: "Siphalor"

repo_name: "GitHub"
repo_url: "https://github.com/Siphalor/nbt-crafting"
edit_uri: "../nbt-crafting-wiki/edit/v1/docs/"

extra:
    logo: "img/logo.png"
    version: "v1"

nav:
    - Home: "index.md"
    - Recipe Parts:
        - Ingredients:
            - Ingredients: "recipe-parts/ingredients/ingredients.md"
            - Remainders: "recipe-parts/ingredients/remainders.md"
        - Results: "recipe-parts/results.md"
    - Recipe Types:
        - Vanilla Recipes: "recipe-types/vanilla.md"
        - Anvil Recipes: "recipe-types/anvil.md"
        - Brewing Recipes: "recipe-types/brewing.md"
        - Cauldron Recipes: "recipe-types/cauldron.md"
        - Modded Recipes: "recipe-types/modded.md"
    - Dynamic Data:
        - Dollars: "dynamic-data/dollars.md"
    - Hints for modders: "modders.md"

markdown_extensions:
    - attr_list
    - admonition
    - fontawesome_markdown
    - pymdownx.details
      #- pymdownx.tabbed
    - pymdownx.tasklist
    - toc:
        permalink: true

theme:
    name: "windmill"
    custom_dir: "custom_theme"
    favicon: "img/favicon.ico"

extra_css:
    - css/extra.css
