site_name: "Nbt Crafting"
site_author: "Siphalor"

repo_name: "GitHub"
repo_url: "https://github.com/Siphalor/nbt-crafting"
edit_uri: "../nbt-crafting-wiki/edit/v1/docs/"

extra:
    logo: "img/logo.png"
    version: "v1"

nav:
    - Home: "index.md"
    - Recipe Parts:
        - Ingredients:
            - Ingredients: "recipe-parts/ingredients/ingredients.md"
            - Remainders: "recipe-parts/ingredients/remainders.md"
        - Results: "recipe-parts/results.md"
    - Recipe Types:
        - Anvil: "recipe-types/anvil.md"
        - Brewing: "recipe-types/brewing.md"
        - Cauldron: "recipe-types/cauldron.md"
    - Dynamic Data:
        - Dollars: "dynamic-data/dollars.md"

markdown_extensions:
    - admonition
    - pymdownx.details
      #- pymdownx.tabbed
    - pymdownx.tasklist
    - toc:
        permalink: true

theme:
    name: "windmill"
    custom_dir: "custom_theme"
    favicon: "img/favicon.ico"
