site_name: "Nbt Crafting"
site_author: "Siphalor"
site_description: "The official wiki of Nbt Crafting v3"
site_url: "https://mcwiki.siphalor.de/nbt-crafting/v3"

repo_name: "GitHub"
repo_url: "https://github.com/Siphalor/nbt-crafting"
edit_uri: "../nbt-crafting-wiki/edit/v3/docs/"

extra:
    logo: "img/logo.png"
    version: "v3"
    nav_links:
      - text: "Nbt Crafting v2"
        icon: "book"
        url: "../v2"
      - text: "Modrinth"
        icon: "chess-rook"
        url: "https://www.modrinth.com/mod/nbt-crafting"
      - text: "Curseforge"
        icon: "fire"
        url: "https://www.curseforge.com/minecraft/mc-mods/nbt-crafting"
      - text: "Discord"
        icon: "discord"
        icon_type: "brand"
        url: "https://discord.gg/6gaXmbj"

nav:
    - Home: "home.md"
    - Updating from v2: "updating.md"
    - Recipe Types:
        - Nbt Recipes: "recipe-types/data.md"
        - Anvil Recipes: "recipe-types/anvil.md"
        - Brewing Recipes: "recipe-types/brewing.md"
        - Cauldron Recipes: "recipe-types/cauldron.md"
        - Modded Recipes: "recipe-types/modded.md"
    - Nbt Capabilities:
        - Ingredients: "nbt-capabilities/ingredients.md"
        - Remainders: "nbt-capabilities/remainders.md"
        - Results: "nbt-capabilities/results.md"
        - Dynamic Data:
            - Dollars: "nbt-capabilities/dynamic-data/dollars.md"
            - Dollar References: "nbt-capabilities/dynamic-data/dollar-references.md"
            - Nbt Merging: "nbt-capabilities/dynamic-data/nbt-merging.md"
    - Hints for modders: "modders.md"
    - JSON Preprocessor: "json-preprocessor.md"
    - Experimental Features: "experimental.md"
    - Resources: "tools.md"

markdown_extensions:
    - attr_list
    - admonition
    - cell_row_span # easy_install https://github.com/Neepawa/cell_row_span/archive/master.zip
    - fontawesome_markdown
    - md_in_html
    - pymdownx.details
      #- pymdownx.tabbed
    - pymdownx.magiclink:
        provider: "github"
        user: "Siphalor"
        repo: "nbt-crafting"
        repo_url_shorthand: true
        repo_url_shortener: true
        normalize_issue_symbols: true
    - pymdownx.snippets:
        base_path:
          - .
          - nbt-crafting/src/testmod/resources/data/nbtcrafting3_testmod/recipes/wiki
        check_paths: true
    - pymdownx.tasklist
    - markdown.extensions.def_list
    - tables
    - toc:
        permalink: true

theme:
    name: "custommill"
    favicon: "img/favicon.ico"
    main_color: "#3e7726"

plugins:
    - mermaid2
    - search

extra_css:
    - css/extra.css
