site_name: "Nbt Crafting"
site_author: "Siphalor"
site_description: "The official wiki of Nbt Crafting 2"
site_url: "https://mcwiki.siphalor.de/nbt-crafting/v2"

repo_name: "GitHub"
repo_url: "https://github.com/Siphalor/nbt-crafting"
edit_uri: "../nbt-crafting-wiki/edit/v2/docs/"

extra:
    logo: "img/logo.png"
    version: "v2"
    nav_links:
      - text: "Nbt Crafting v1"
        icon: "book"
        url: "../v1"
      - text: "Modrinth"
        icon: "chess-rook"
        url: "https://www.modrinth.com/mod/nbt-crafting"
      - text: "Curseforge"
        icon: "fire"
        url: "https://www.curseforge.com/minecraft/mc-mods/nbt-crafting"
      - text: "Discord"
        icon: "discord"
        icon_type: "brand"
        url: "https://discord.gg/6gaXmbj"

nav:
    - Home: "home.md"
    - Recipe Parts:
        - Ingredients:
            - Ingredients: "recipe-parts/ingredients/ingredients.md"
            - Remainders: "recipe-parts/ingredients/remainders.md"
        - Results: "recipe-parts/results.md"
    - Recipe Types:
        - Vanilla Recipes: "recipe-types/vanilla.md"
        - Anvil Recipes: "recipe-types/anvil.md"
        - Brewing Recipes: "recipe-types/brewing.md"
        - Cauldron Recipes: "recipe-types/cauldron.md"
        - Modded Recipes: "recipe-types/modded.md"
    - Dynamic Data:
        - Dollars: "dynamic-data/dollars.md"
        - Dollar References: "dynamic-data/dollar-references.md"
        - Nbt Merging: "dynamic-data/nbt-merging.md"
    - Hints for modders: "modders.md"
    - Utilities: "utilities.md"
    - Updating to v2: "updating.md"
    - Experimental Features: "experimental.md"
    - Resources: "tools.md"

markdown_extensions:
    - attr_list
    - admonition
    - cell_row_span # easy_install https://github.com/Neepawa/cell_row_span/archive/master.zip
    - fontawesome_markdown
    - md_in_html
    - pymdownx.details
      #- pymdownx.tabbed
    - pymdownx.tasklist
    - tables
    - toc:
        permalink: true

theme:
    name: "custommill"
    favicon: "img/favicon.ico"
    main_color: "#3e7726"

extra_css:
    - css/extra.css
